USE `otter`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for DATA_MEDIA_PAIR
-- ----------------------------
DROP TABLE IF EXISTS `DATA_MEDIA_PAIR`;
CREATE TABLE `DATA_MEDIA_PAIR` (
                                   `ID` bigint(20) NOT NULL AUTO_INCREMENT,
                                   `PULLWEIGHT` bigint(20) DEFAULT NULL,
                                   `PUSHWEIGHT` bigint(20) DEFAULT NULL,
                                   `RESOLVER` text DEFAULT NULL,
                                   `FILTER` text DEFAULT NULL,
                                   `SOURCE_DATA_MEDIA_ID` bigint(20) DEFAULT NULL,
                                   `TARGET_DATA_MEDIA_ID` bigint(20) DEFAULT NULL,
                                   `PIPELINE_ID` bigint(20) NOT NULL,
                                   `COLUMN_PAIR_MODE` varchar(20) DEFAULT NULL,
                                   `GMT_CREATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
                                   `GMT_MODIFIED` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                                   PRIMARY KEY (`ID`),
                                   KEY `idx_PipelineID` (`PIPELINE_ID`,`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of DATA_MEDIA_PAIR
-- ----------------------------
BEGIN;
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (1, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661503000152}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661503000152}', 1, 11, 3, 'INCLUDE', '2022-08-26 16:36:40', '2022-08-26 16:36:40');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (2, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661503223667}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661503223667}', 2, 12, 3, 'INCLUDE', '2022-08-26 16:40:23', '2022-08-26 16:40:23');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (3, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661503990965}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661503990965}', 3, 13, 3, 'INCLUDE', '2022-08-26 16:53:10', '2022-08-26 16:53:10');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (4, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1664329093507}', '{\"blank\":true,\"extensionDataType\":\"SOURCE\",\"notBlank\":false,\"sourceText\":\"\",\"timestamp\":1664329093507}', 4, 14, 3, 'INCLUDE', '2022-08-26 16:53:29', '2022-09-28 09:38:13');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (5, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504022912}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504022912}', 5, 15, 3, 'INCLUDE', '2022-08-26 16:53:42', '2022-08-26 16:53:42');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (6, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504039881}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504039881}', 6, 16, 3, 'INCLUDE', '2022-08-26 16:53:59', '2022-08-26 16:53:59');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (7, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504051594}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504051594}', 7, 17, 3, 'INCLUDE', '2022-08-26 16:54:11', '2022-08-26 16:54:11');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (8, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504079395}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504079395}', 8, 18, 3, 'INCLUDE', '2022-08-26 16:54:39', '2022-08-26 16:54:39');
-- INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (9, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1664328213133}', '{\"blank\":true,\"extensionDataType\":\"SOURCE\",\"notBlank\":false,\"sourceText\":\"\",\"timestamp\":1664328213133}', 9, 19, 3, 'INCLUDE', '2022-08-26 16:54:53', '2022-09-28 09:23:33');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (9, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1667530333646}', '{\"blank\":false,\"extensionDataType\":\"SOURCE\",\"notBlank\":true,\"sourceText\":\"package com.alibaba.otter.node.extend.processor;\\r\\n\\r\\nimport com.alibaba.otter.shared.etl.model.EventData;\\r\\nimport org.apache.commons.lang.StringUtils;\\r\\n\\r\\npublic class TableEventProcessor  extends AbstractEventProcessor {\\r\\n\\r\\n    @Override\\r\\n    public boolean process(EventData eventData) {\\r\\n\\r\\n        if (StringUtils.equals(\\\"dcmc_login_fail\\\", eventData.getTableName())) {\\r\\n            return false;\\r\\n        }\\r\\n\\r\\n        return true;\\r\\n\\r\\n\\r\\n    }\\r\\n}\",\"timestamp\":1667530333646}', 9, 19, 3, 'INCLUDE', '2022-08-26 16:54:53', '2022-11-04 10:52:13');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (10, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504105123}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504105123}', 10, 20, 3, 'INCLUDE', '2022-08-26 16:55:05', '2022-08-26 16:55:05');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (13, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504325473}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504325473}', 11, 1, 4, 'INCLUDE', '2022-08-26 16:58:45', '2022-08-26 16:58:45');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (14, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504336156}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504336156}', 12, 2, 4, 'INCLUDE', '2022-08-26 16:58:56', '2022-08-26 16:58:56');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (15, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504348749}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504348749}', 13, 3, 4, 'INCLUDE', '2022-08-26 16:59:08', '2022-08-26 16:59:08');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (16, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1664329103860}', '{\"blank\":true,\"extensionDataType\":\"SOURCE\",\"notBlank\":false,\"sourceText\":\"\",\"timestamp\":1664329103860}', 14, 4, 4, 'INCLUDE', '2022-08-26 16:59:21', '2022-09-28 09:38:23');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (17, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504378755}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504378755}', 15, 5, 4, 'INCLUDE', '2022-08-26 16:59:38', '2022-08-26 16:59:38');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (18, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504397240}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504397240}', 16, 6, 4, 'INCLUDE', '2022-08-26 16:59:57', '2022-08-26 16:59:57');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (19, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504413959}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504413959}', 17, 7, 4, 'INCLUDE', '2022-08-26 17:00:13', '2022-08-26 17:00:13');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (20, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504437445}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504437445}', 18, 8, 4, 'INCLUDE', '2022-08-26 17:00:37', '2022-08-26 17:00:37');
-- INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (21, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1664328204218}', '{\"blank\":true,\"extensionDataType\":\"SOURCE\",\"notBlank\":false,\"sourceText\":\"\",\"timestamp\":1664328204218}', 19, 9, 4, 'INCLUDE', '2022-08-26 17:00:52', '2022-09-28 09:23:24');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (21, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1667530324836}', '{\"blank\":false,\"extensionDataType\":\"SOURCE\",\"notBlank\":true,\"sourceText\":\"package com.alibaba.otter.node.extend.processor;\\r\\n\\r\\nimport com.alibaba.otter.shared.etl.model.EventData;\\r\\nimport org.apache.commons.lang.StringUtils;\\r\\n\\r\\npublic class TableEventProcessor  extends AbstractEventProcessor {\\r\\n\\r\\n    @Override\\r\\n    public boolean process(EventData eventData) {\\r\\n\\r\\n        if (StringUtils.equals(\\\"dcmc_login_fail\\\", eventData.getTableName())) {\\r\\n            return false;\\r\\n        }\\r\\n\\r\\n        return true;\\r\\n\\r\\n\\r\\n    }\\r\\n}\",\"timestamp\":1667530324836}', 19, 9, 4, 'INCLUDE', '2022-08-26 17:00:52', '2022-11-04 10:52:04');
INSERT INTO `otter`.`DATA_MEDIA_PAIR`(`ID`, `PULLWEIGHT`, `PUSHWEIGHT`, `RESOLVER`, `FILTER`, `SOURCE_DATA_MEDIA_ID`, `TARGET_DATA_MEDIA_ID`, `PIPELINE_ID`, `COLUMN_PAIR_MODE`, `GMT_CREATE`, `GMT_MODIFIED`) VALUES (22, NULL, 5, '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504464147}', '{\"blank\":true,\"clazzPath\":\"\",\"extensionDataType\":\"CLAZZ\",\"notBlank\":false,\"timestamp\":1661504464147}', 20, 10, 4, 'INCLUDE', '2022-08-26 17:01:04', '2022-08-26 17:01:04');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;